### ISSUE TITLE
Fix the Netlify hosting

### ISSUE THREAD

**Issue by xaviablaza** [UXSoc/Docs#7]
## Description
- Fix the Netlify hosting

Netlify installs twice cause the packages.json file in the root isn't the one used my the website itself,
Netlify automatically installs the root package.json, but thats isn't needed
Instead of running 'yarn build' I have to run `cd /website && yarn && yarn install`
That increases deploy times

**Comment by jhburns** [comment]
Fixed, changed base dir to website/
